// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quisco.DataAccess;

namespace Quisco.DataAccess.Migrations
{
    [DbContext(typeof(QuiscoContext))]
    [Migration("20190428162045_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quisco.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("QuestionId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Quisco.Model.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Question1QuestionId");

                    b.Property<int?>("Question2QuestionId");

                    b.Property<int?>("Question3QuestionId");

                    b.Property<int?>("Question4QuestionId");

                    b.Property<string>("QuizCategory")
                        .HasMaxLength(20);

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("QuizId");

                    b.HasIndex("Question1QuestionId");

                    b.HasIndex("Question2QuestionId");

                    b.HasIndex("Question3QuestionId");

                    b.HasIndex("Question4QuestionId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Quisco.Model.Quiz", b =>
                {
                    b.HasOne("Quisco.Model.Question", "Question1")
                        .WithMany()
                        .HasForeignKey("Question1QuestionId");

                    b.HasOne("Quisco.Model.Question", "Question2")
                        .WithMany()
                        .HasForeignKey("Question2QuestionId");

                    b.HasOne("Quisco.Model.Question", "Question3")
                        .WithMany()
                        .HasForeignKey("Question3QuestionId");

                    b.HasOne("Quisco.Model.Question", "Question4")
                        .WithMany()
                        .HasForeignKey("Question4QuestionId");
                });
#pragma warning restore 612, 618
        }
    }
}
