// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quisco.DataAccess;

namespace Quisco.DataAccess.Migrations
{
    [DbContext(typeof(QuiscoContext))]
    partial class QuiscoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quisco.Model.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssociatedQuizQuizId");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.HasKey("QuestionId");

                    b.HasIndex("AssociatedQuizQuizId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("Quisco.Model.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("QuizCategory")
                        .HasMaxLength(20);

                    b.Property<string>("QuizName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("QuizId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Quisco.Model.Question", b =>
                {
                    b.HasOne("Quisco.Model.Quiz", "AssociatedQuiz")
                        .WithMany("Questions")
                        .HasForeignKey("AssociatedQuizQuizId");
                });
#pragma warning restore 612, 618
        }
    }
}
